development:
  adapter: postgresql
  encoding: unicode
  database: kbeez_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: kbeez_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: kbeez_production
  pool: 5
